# Generated by Django 3.2.11 on 2024-02-25 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('currensy', models.CharField(choices=[('btc', 'BTC'), ('usdt', 'USDT')], default='usdt', max_length=6)),
                ('operation', models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], default='buy', max_length=6)),
                ('amount_give', models.IntegerField()),
                ('amount_get', models.IntegerField()),
                ('where_send_money', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
